export const StartIn = {
	image: "pictures",
	video: "videos",
	audio: "music",
	document: "documents",
	archive: "documents",
	text: "documents",
	font: "documents",
	application: "documents",
	ebook: "documents",
	database: "documents",
	config: "documents",
	vector: "documents",
	"3d": "documents",
	virtualization: "documents",
	container: "documents",
	certificate: "documents",
	script: "documents",
	markup: "documents",
	calendar: "documents",
	contact: "documents",
};
